### PR TITLE
Icon Fixes/Additons

### PR DESCRIPTION
**Pull request by Agent-Theta**
Fixed some misspelled icon names causing them to be invisible on map (S4, S5, S6). Added tomato yoshi icon for his area in s6 to replace scar head (should have been renthedog head to begin with). moved all demise locations to the demise heading (S6). added Halloween district loc in place of deadquarters (which was moved to demise) (S6).

### CODE REVIEW

**Comment by Dinip** [comment]
oh, thanks for the fixes in s4 and s5 🙂
about the tomato yoshi icon that you uploaded, it is 8x8px, can't you get a icon at least 24x24?

**Comment by Agent-Theta** [comment]
ah whoops missed that they were all 24X24 will try to fix that. i just threw it together from the skins, will see how you do it.

**Comment by Agent-Theta** [comment]
done. By any chance are you planning on doing the farms and shops for S7? And also bases shops and games for S3? i know S3 all over, spent years exploring it when i was watching S4 and waiting for that world :)

**Comment by Agent-Theta** [comment]
I was doing all this way past the time i usually go to bed, so i missed that small detail on the icons even though i had been staring at the lines of code that said 24X24 over and over :P

**Comment by Dinip** [comment]
> done. By any chance are you planning on doing the farms and shops for S7? And also bases shops and games for S3? i know S3 all over, spent years exploring it when i was watching S4 and waiting for that world :)
What you mean by "planning on doing the farms and shops"? Do you mean having separate categories for the markers?

**Comment by Agent-Theta** [comment]
what i am asking is if it is fine if i make a category for farms and one for shops and then collect all the locations of the shops and farms and put them into those categories. and then for S3 have three more categories and put the bases in one, shops in another, and then games in the last. maybe not do the shops though

**Comment by Dinip** [comment]
Sure, anyone can edit the file to fit the needs. I will always check it before the commit just to prevent abuse. The most "complete" file is the season6 file and you can check how the "categories" work if you have difficulties but I my opinion is not that hard 😃
I will close this pull request to commit the changes, if you need something you can always open an issue or contact me via discord, for example!
Thanks for helping!! 🙂

**Pull request closed without merging**
