### PR TITLE
Season 9

### PR DESCRIPTION
**Pull request by Huntracony**
The bases I'm adding are based on the world download provided by Cortex (see [this](https://www.reddit.com/r/HermitCraft/comments/ta5eaj/hermitcraft_season_9_seed_world_download/) Reddit post).  I'm assuming the coordinates are the same as the actual seed but I haven't confirmed that.

### CODE REVIEW

**Comment by Huntracony** [comment]
Missing Doc, xB, Hypno, Cleo, and Etho's starter bases.  First three I can't be bothered, last two don't have one yet.
Also, I think Ren and Cub are basing together but I watch neither of them so I'm not entirely sure.

**Comment by Dinip** [comment]
Yep, I saw the post from Cortex. Yesterday I was actually thinking in rendering the empty map as I did before but I couldn't find the seed, then I saw the post from Cortex talking about it. Now idk if I should render the empty map or not (since it has most, if not all structures removed), I haven't seen the map yet but from the description thats what I think.

**Comment by Huntracony** [comment]
Yeah, it has no villages or dungeons or anything.  In my opinion they aren't that important anyway, but if you wanna wait I got the feeling the seed will be released within the next couple of weeks anyway.

**Comment by Dinip** [comment]
well, seems to be time to render the empty map 🤔 
and maybe also merge this PR

**Comment by Huntracony** [comment]
:D

**Comment by Dinip** [comment]
I think I'll generate it with the center on `-1750 64 1500` (spawn coords from reddit post) 🤔 
Do you know if the have a border? If so what is the distance?

**Comment by Huntracony** [comment]
The other directions don't have a border

**Comment by Huntracony** [comment]
Replying to the email apparently didn't work.  1500 blocks south of spawn is the worldborder

**Comment by Dinip** [comment]
merging to release the empty map soon

**Comment by Huntracony** [comment]
The season 9 info thread says 1500 blocks south of spawn

**Pull request merged**
