### PR TITLE
Big Eye Come On In and Buy! all 6 location

### PR DESCRIPTION
**Pull request by AamerQa**

### CODE REVIEW

**Comment by Dinip** [comment]
there is no bigeye.png

**Comment by AamerQa** [comment]
I tried to upload 3 new Icons " bigeye + Tango and Bdubs new face icon " but it seemed I didn't do it right :(

am sorry this the first time I try to contribute to this :)
is there any way to upload the icons?

**Comment by AamerQa** [comment]
I uploaded the icons on issues if you want have a look
sorry for the inconvenience!

**Comment by Dinip** [comment]
tango and bdubs icons already exist, only bigeye was missing. I'll get it from the issue and upload it to the main repo.
again, please keep the file organized by the icon name😉

**Comment by Dinip** [comment]
Thanks 👍

**Pull request merged**
