### PR TITLE
Added Welsknight's, Etho and Iskalls starter base

### PR DESCRIPTION
**Pull request by Joesv**

### CODE REVIEW

**Comment by Joesv** [comment]
For Wels' base I have chosen the front door for the cords.

Etho and Iskall don't really have a specific entrance so I have chosen the center of the room with the tree.

**Comment by Dinip** [comment]
Thanks 👊

**Comment by Dinip** [comment]
lol I missed it... the Y and Z coords are swaped, here the format it [X, Z, Y] and not the minecraft standard [X, Y, Z]. I'll fix it but if you add more markers, take that into account 😉

**Comment by Joesv** [comment]
Will do!

**Comment by Dinip** [comment]
Thanks! 👍

**Pull request merged**
