### PR TITLE
Aligning S7 markers with map

### PR DESCRIPTION
**Pull request by WeirdAlex03**
Most markers on the S7 map were estimated before the world download was made available, and thus are slightly off from the actual locations. I'm mostly aligning them to either the front door or center block

- [x] Bases
- [x] Minigames
- [x] Farms
- [x] Shops
- [x] Turf War
- [x] Other

### CODE REVIEW

**Comment by Dinip** [comment]
Uhh! That's nice! Waiting for the draft to be complete 👀

**Comment by WeirdAlex03** [comment]
> All minigames/events, moved Frankenstien to events

Yes, I know it's Frankenstein's _monster_ but I ran out of characters in the commit message. I also misspelled the name. That one's on me.

**Comment by WeirdAlex03** [comment]
One month in the making, I have now gone through and updated all 188 S7 markers to align them with the builds on the map, and resolved the merge conflict with the other changes made since then (though I'm still not exactly sure how I accomplished that, I just tried stuff until it worked).

Now time to put this behind me and never think about this project again. Well, at least until some time in 2022 or 2023 when S8 ends

**Comment by Dinip** [comment]
WOW! YOU ARE AMAZING! Great job! Thanks for helping the project!

> though I'm still not exactly sure how I accomplished that, I just tried stuff until it worked

That's the daily bases of a programmer 

Well, let's merge it! 👊

**Comment by WeirdAlex03** [comment]
Uh oh, looks like I have a few fixes to make... Trader Jev's has been dumped in the ocean, ScarX has been donated to Xisuma, and a couple shops got shuffled. I'll take care of that as soon as I can

The rest of it looks really good though, I think it was worth it in the end!

**Comment by WeirdAlex03** [comment]
Just checked everything on the map and this is the full list. I'll make a new PR when I knock these out

**Corrections to make:**
- Bases
  - [ ] ScarX
- Events
  - [ ] Frankenstein's Monster
- Farms
  - [ ] BDubs Creeper Farm
- Shops
  - [ ] Trader Jev's
  - [ ] X Blackstone Shop
  - [ ] False Warped Realm
  - [ ] Ice-E-E's
  - [ ] LLAMB
  - [ ] Hypno Trident shop
- Turf War
  - [ ] HEP HQ
- Others
  - [ ] Christmas District
  - [ ] Mt Scarmore

**Pull request merged**
